[pytest]
markers =
    provider(name): mark test as specific to a given quantum provider (e.g. qiskit, cirq, braket, azure, myqlm, quantinuum)
; culprits packages added as comments
filterwarnings = 
    ;  pyreadline
    ignore::DeprecationWarning
    ; pytket-qiskit still instantiates Qiskit Aer's legacy simulator classes
    ignore:The `QasmSimulator` backend will be deprecated in the future\.:PendingDeprecationWarning
    ignore:The `StatevectorSimulator` backend will be deprecated in the future\.:PendingDeprecationWarning
    ignore:The `UnitarySimulator` backend will be deprecated in the future\.:PendingDeprecationWarning
