[pytest]
markers =
    provider(name): mark test as specific to a given quantum provider (e.g. qiskit, cirq, braket, azure, myqlm)
; culprits packages added as comments
filterwarnings = 
    ;  pyreadline
    ignore::mpqp.qasm.qasm_to_braket.UnsupportedBraketFeaturesWarning
    ignore::mpqp.qasm.open_qasm_2_and_3.OpenQASMTranslationWarning
    ignore::DeprecationWarning