[pytest]
testpaths = tests
markers =
    provider(name): mark test as specific to a given quantum provider (e.g. qiskit, cirq, braket, azure, myqlm)
    performance: performance benchmark (run separately from the functional test suite)
; culprits packages added as comments
filterwarnings = 
    ;  pyreadline
    ignore::DeprecationWarning
