name: Black Formatter

on:
  push:
    branches:
      - '*'

jobs:
  black:
    name: Format code with Black
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black

    - name: Run Black
      run: black
      #run: black .

    - name: Show Black changes
      run: |
        git diff --name-only
        git diff

