name: Documentation deployement

on:
  pull_request_target:
    types:
      - closed
    branches:
      - main
  release:
    types: [published]
jobs:
  build_publish_docs:
    # Deploy to cloudflare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Document
        env:
          SPHINX_GITHUB_CHANGELOG_TOKEN: ${{ secrets.DOC_GH_API_TOKEN || github.token }}
        run: |
          pip install -r requirements-dev.txt
          sudo apt update
          sudo apt install -y pandoc
          sphinx-build -b html docs build
      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.PRD_CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.PRD_CLOUDFLARE_ACCOUNT_ID }}
          projectName: mpqp
          branch: main
          directory: build
