name: PyPI publishing

on:
  push:
    tags:
      - "*"

jobs:
  build_publish_package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install build tools
        run: python -m pip install --upgrade build twine
      - name: Build Package
        run: python -m build
      - name: Check distributions
        run: twine check dist/*
      - name: Publish to PyPI
        run: twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PRD_QT_API_TOKEN }}
