name: Tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
  workflow_dispatch:
    inputs:
      python_v:
        description: "python version"
        required: true
        default: "3.9"
        type: choice
        options:
          - "3.9"
          - "3.10"
          - "3.11"
      commit_ref:
        description: Specific ref (branch, tag or SHA)
        default: ""
        type: string
        required: false
      long:
        description: "Run long tests"
        required: false
        default: false
        type: boolean
      providers:
        description: "Providers to enable (space-separated) e.g., 'qiskit cirq myqlm braket')"
        required: false
        default: "all"
        type: string

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        python-version: ${{ fromJSON(github.event_name == 'workflow_dispatch' && format('["{0}"]', github.event.inputs.python_v) || '["3.9", "3.10", "3.11"]') }}
        provider: ${{ fromJSON(github.event_name == 'workflow_dispatch' && format('["{0}"]', github.event.inputs.providers) || (github.ref_name == 'main' && '["all", "qiskit", "cirq", "braket", "myqlm"]' || '["all"]')) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.commit_ref || github.ref }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install python dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements-dev.txt
          providers_comma=$(echo "${{ matrix.provider }}" | sed 's/ /,/g')
          echo $providers_comma
          pip install .[$providers_comma]
      - name: Install os specific dependencies
        if: ${{ github.event.inputs.long == 'true' || github.ref_name == 'main' }}
        run: |
          sudo apt-get update
          sudo apt install -y poppler-utils
          sudo apt-get install -y texlive-latex-base texlive-pictures texlive-latex-extra
      - name: Run tests
        run: |
          if [[ "${{ matrix.provider }}" == "all" && ( "${{ github.event.inputs.long }}" == "true" || "${{ github.ref_name }}" == "main" ) ]]; then
            python -m pytest --long-local 
          else
            python -m pytest --providers ${{ matrix.provider }}
          fi
  typechecks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ${{ fromJSON(github.event_name == 'workflow_dispatch' && format('["{0}"]', github.event.inputs.python_v) || '["3.9", "3.10", "3.11"]') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.commit_ref || github.ref }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install -r requirements-all.txt
      - name: Run type checker
        run: pyright